### PR TITLE
Code climate

### PR DESCRIPTION
**Pull request by dsager**

### CODE REVIEW

**Comment by towanda** [comment]
+1

**Comment by yaneq** [comment]
+1

**Comment by psyfear** [comment]
This is nice. Do we now have an account on code climate that we can experiment on? Would love to add this on our other repos.

**Comment by dsager** [comment]
No, we don't have a subscription. This is a open source repository, so it's free. Same goes for Travis CI...

**Comment by psyfear** [comment]
I was talking about this: https://codeclimate.com/tour with this pricing: https://codeclimate.com/pricing

I guess we have the same setup on Jenkins which uses Rubocop, so I'm not sure if its comparatively better. I have colleagues who uses it with great praise though.

**Comment by ifosch** [comment]
Probably not related only to that PR, but, shouldn't it include the Gemfile.lock?

**Comment by dsager** [comment]
No, for libraries you usually don't have the .lock file under version control ...

I also like code climate, but for our app stack Jenkins is the better choice I guess. I just set it up for this repo since it's open source and the service therefore free. But who knows, if we like it a lot we might consider using it for the other repos as well...

**Comment by christofdamian** [comment]
we have most of the information of codeclimate also available in jenkins
and more importantly locally.

it is just that nobody ever looks at it

**Pull request merged**
